### ISSUE TITLE
Make net.go:conn.Send() thread safe

### ISSUE THREAD

**Issue by samribeiro** [netrack/openflow#125]

**Comment by ybubnov** [comment]
@samribeiro , thank you for posting the issue, appreciate it!

Would it be better to define two implementations of ```Conn``` interface:
- one is thread-unsafe (current one), which is used in ```Server``` to handle connections
- another one is thread-safe, which is returned from ```NewConn``` constructor and probably from ```Request.Conn``` function?

So my proposition is to change the ```conn``` to ```unsafeConn``` and implement a new type ```conn``` with the following signature:
```go
type unsafeConn struct {
        // ...
}

// conn overrides Write and Flush methods of unsafe connection.
type conn struct {
         unsafeConn
         mu sync.Mutex
}
```

What is your opinion on this?

**Comment by samribeiro** [comment]
Hi ybubnov@, thanks for the suggestion.

I think it sounds good as long as I can use `safeConn` in `Server`? One can use `Server` and `ServeMux` with specific handlers while at the same time use the same `Conn`'s for side threaded writes. 

On the other side I am unsure why would you want to keep `unsafeConn`? As long as you expose `Conn` to the application, you are pitting the application for trouble in case it uses threads.

**Comment by ybubnov** [comment]
I see your point now - the connection will be used simultaneously within a server and some routine (that can write messages to it. In such scenario ```unsafeConn``` is useless. Initially I thought that it would be wise to use unsafe connection for the sake of performance (e.g. acquire a lock per write/flush pair instead of per each operation).

I agree with your solution, but I believe locking mechanism in the ```Server``` should be revised according to the new approach - probably some locks a redundant now.
